---
title: "Combined meta-analysis"
author: "Sofia Salazar"
date: "2023-02-15"
output: html_document
---


```{bash}
qlogin
cd /mnt/Citosina/amedina/ssalazar/meta/out
module load r/4.0.2
R
```


# Annotate gene symbol

```{r gene symbol}
library(tidyverse)
outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/"
load(paste0(outdir, "LRT-dds.RData"))
DGE <- res2
# annotate genes with symbol

df <- as.data.frame(DGE)
df <- tibble::rownames_to_column(df, "ID")
name_short<-function(table){
  table$ID <- gsub("\\..*","", table$ID)
  return(table)
}

df <- name_short(df)

library("biomaRt")
mart <- useMart(biomart="ensembl", dataset="hsapiens_gene_ensembl")
genes <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol","transcript_biotype"),
                          filters = c("ensembl_gene_id"), 
                          values = df$ID,
                          mart = mart)
names(genes)[1] <- "ID"
names(genes)[2] <- "gene_name"

protein_coding<-subset(genes, transcript_biotype =="protein_coding")
dim(protein_coding[unique(protein_coding$gene_name),])
non.dup <- protein_coding[!duplicated(protein_coding$gene_name),]

non.dup <- non.dup[!(is.na(non.dup$gene_name)),]

df_names <- list(df, non.dup) %>% purrr::reduce(inner_join, by = "ID")

write.csv(df_names, file = paste0(outdir,"DGElist_withNames.csv"))
```

```{r}
save.image(file = paste0(outdir,"namedDGElist.RData"))
load("/mnt/Citosina/amedina/ssalazar/meta/combined/namedDGElist.RData")
```

# with non-coding genes

```{r}
dim(dds2) # 49465
dim(df) # 49465
dim(genes[unique(genes$gene_name),]) # 35119
dim(df[unique(df$ID),]) # 
df_names_all <- list(df, genes) %>% purrr::reduce(inner_join, by = "ID")
dim(df_names_all[unique(df_names_all$ID),])# 76982  
write.csv(df_names_all, file = paste0(outdir,"DGElist_withNames_noncoding.csv"))
```


# Downregulated and upregulated genes

```{r Down and Up genes}
upGenes <- subset(df_names, padj < 0.05 & log2FoldChange >= 1)
veryUP <- subset(df_names, padj < 0.05 & log2FoldChange >= 2)

downGenes <- subset(df_names, padj < 0.05 & log2FoldChange <= -0.5)
veryDOWN <- subset(df_names, padj < 0.05 & log2FoldChange <= -2)
```


# Volcano Plot

```{r Volcano Plot}
library(ggplot2)
data <- df_names %>% 
  mutate(Expression = case_when(log2FoldChange >= 1 & padj < 0.05 ~ "Up-regulated",
                                log2FoldChange <= -1 & padj < 0.05 ~ "Down-regulated",
                                TRUE ~ "Unchanged"))
head(data) %>% 
  knitr::kable()

volcanoplot <- ggplot(data, aes(log2FoldChange, -log(padj,10))) +
  geom_point(aes(color = Expression), size = 2/5) +
  xlab(expression("log"[2]*"FC")) + 
  ylab(expression("-log"[10]*"p-adj")) +
  scale_color_manual(values = c("dodgerblue3", "gray50", "firebrick3")) +
  guides(colour = guide_legend(override.aes = list(size=1.5))) 

data %>% 
  count(Expression) %>% 
  knitr::kable()


top <- 10
top_genes <- bind_rows(data %>% 
    filter(Expression == 'Up-regulated') %>% 
    arrange(padj, desc(abs(log2FoldChange))) %>% 
    head(top),
  data %>% 
    filter(Expression == 'Down-regulated') %>% 
    arrange(padj, desc(abs(log2FoldChange))) %>% 
    head(top)
)
top_genes %>% 
  knitr::kable()

volcanoplot_names <-  volcanoplot +
  ggrepel::geom_label_repel(data = top_genes,
                   mapping = aes(log2FoldChange, -log(padj,10), label = gene_name),
                   size = 2)

ggsave(paste0(outdir,"volcanoPlotWithTopGenes.png"),
       plot = p3, dpi = 300)
dev.off()
```

# GO terms

```{r GO terms}
library(gprofiler2)
library(enrichplot)
library(DOSE)
library(clusterProfiler)
library(ggplot2)

up <- data %>%filter(Expression == 'Up-regulated') %>% 
  arrange(padj, desc(abs(log2FoldChange)))

down <- data %>%filter(Expression == 'Down-regulated') %>% 
  arrange(padj, desc(abs(log2FoldChange)))

# up_ordered <- head(upGenes[order(upGenes$log2FoldChange, decreasing = TRUE),],15)
# down_ordered <- head(downGenes[order(downGenes$log2FoldChange, decreasing = TRUE),],15)


multi_gp <- gost(list("Upregulated" = up$gene_name, "Downregulated" = down$gene_name), correction_method = "fdr", multi_query = F, ordered_query = T, organism = 'hsapiens')

# save(multi_gp, file = paste0(outdir,'GO_query.RData'))

gostp1 <- gostplot(multi_gp, interactive = FALSE)
ggsave(paste0(outdir,"manhattanGO.png"),
       plot = gostp1, dpi = 300)
dev.off()

# gostp1

gost_query <- as.data.frame(multi_gp$result)

plot_data <- data.frame("term" = as.factor(gost_query$term_name), "condition" = gost_query$query, "GeneRatio" = gost_query$intersection_size / gost_query$query_size, "p.adjust" = gost_query$p_value, 'category' = as.factor(gost_query$source))

plot_data_up <- subset(plot_data, condition == 'Upregulated')
plot_data_up <- head(plot_data_up[order(plot_data_up$p.adjust),],15)

plot_data_down <- subset(plot_data, condition == 'Downregulated')
plot_data_down <- head(plot_data_down[order(plot_data_down$p.adjust),],15)

plot_data_reduced <- rbind(plot_data_up, plot_data_down)

# Dotplot
dotplot <- ggplot(data = plot_data_reduced, aes(x = condition, y = term,
                        color = p.adjust, size = GeneRatio)) +
  geom_point(aes(shape = category)) +
  scale_color_gradient(low = "#EF769C", high = "#EFD09C") +
  theme_gray() + 
  ylab("") + 
  xlab("") + 
  ggtitle("GO enrichment analysis")

ggsave(paste0(outdir,"dotplotGO.png"),
       plot = dotplot, dpi = 300)
dev.off()

# Barplot

#df2=data.frame(class=sample(c("BP","MF","CC"), 30, replace=T), "GO Term"=paste0("term_", sample(1:30, 30, replace = F)), count=sample(10:30, 30, replace = T), comparison=sample(c("A","B","C"), 30, replace = T))

bar_data <- data.frame("term" = as.factor(gost_query$term_name), "condition" = gost_query$query, "count" = gost_query$term_size, "p.adjust" = gost_query$p_value, 'category' = as.factor(gost_query$source))


bar_data_up <- subset(bar_data, condition == 'Upregulated')
bar_data_up <- head(bar_data_up[order(bar_data_up$p.adjust),],15)

bar_data_down <- subset(bar_data, condition == 'Downregulated')
bar_data_down <- head(bar_data_down[order(bar_data_down$p.adjust),],15)

bar_data_reduced <- rbind(bar_data_up, bar_data_down)

bar_data_ordered <- bar_data_reduced[order(bar_data_reduced$count),] # order by count
bar_data_ordered<- bar_data_ordered[order(bar_data_ordered$category),] # order by category
bar_data_ordered$num <- seq(1:nrow(bar_data_ordered)) # num category for plot

g <- ggplot(bar_data_ordered, aes(count, reorder(term, -num), fill = category)) +
    geom_bar(stat = "identity") +
    geom_text(
        aes(label = count),
        color = "black",
        hjust = -0.1,
        size = 4,
        position = position_dodge(0.9)
    ) +
  labs(x = "Gene counts" ) +
  scale_fill_manual(name='Category', labels = c('Biological Process', 'Cellular Component',
                                                  'Molecular Function', 'REAC'), values = c('#3C6997', '#DD7230','#B4DC7F','#25ced1')) +
  theme(
        legend.position = "right",
        # panel.grid = element_blank(),
        # axis.text.x = element_blank(),
        # axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold"),
        strip.background = element_blank()
    )

ggsave(paste0(outdir,"barplotGO.png"),
       plot = g, dpi = 300, width = 20, height = 10)
dev.off()

## barplot only upregulated

bar_data_up <- subset(bar_data, condition == 'Upregulated')
bar_data_up <-head(bar_data_up[order(bar_data_up$p.adjust),],40) # order by pvalue
bar_data_up_ordered <- bar_data_up[order(bar_data_up$count),] # order by count
bar_data_up_ordered<- bar_data_up_ordered[order(bar_data_up_ordered$category),] # order by category
bar_data_up_ordered$num <- seq(1:nrow(bar_data_up_ordered)) # num category for plot

g.up <- ggplot(bar_data_up_ordered, aes(count, reorder(term, -num), fill = category)) +
    geom_bar(stat = "identity") +
    geom_text(
        aes(label = count),
        color = "black",
        hjust = -0.1,
        size = 4,
        position = position_dodge(0.9)
    ) +
  labs(x = "Gene counts" ) +
 scale_fill_manual(name='Category', labels = c('Biological Process', 'REAC', 'TF'), values = c('#3C6997', '#DD7230','#B4DC7F','#25ced1')) +
  theme(
        legend.position = "right",
        # panel.grid = element_blank(),
        # axis.text.x = element_blank(),
        # axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold"),
        strip.background = element_blank()
    )

ggsave(paste0(outdir,"barplotUP_GO.png"),
       plot = g.up, dpi = 300, width = 20, height = 10)
dev.off()

## barplot only downregulated

bar_data_down <- subset(bar_data, condition == 'Downregulated')
bar_data_down <-head(bar_data_down[order(bar_data_down$p.adjust),],40) # order by pvalue
bar_data_down_ordered <- bar_data_down[order(bar_data_down$count),] # order by count
bar_data_down_ordered<- bar_data_down_ordered[order(bar_data_down_ordered$category),] # order by category
bar_data_down_ordered$num <- seq(1:nrow(bar_data_down_ordered)) # num category for plot

g.down <- ggplot(bar_data_down_ordered, aes(count, reorder(term, -num), fill = category)) +
    geom_bar(stat = "identity") +
    geom_text(
        aes(label = count),
        color = "black",
        hjust = -0.1,
        size = 4,
        position = position_dodge(0.9)
    ) +
  labs(x = "Gene counts" ) +
 scale_fill_manual(name='Category', labels = c('CORUM', 'Biological Process', 'Cellular Component', 'Molecular Function'), values = c('#e810cb', '#3C6997','#d9c621','#b30039')) +
  theme(
        legend.position = "right",
        # panel.grid = element_blank(),
        # axis.text.x = element_blank(),
        # axis.ticks = element_blank(),
        axis.title.y = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold"),
        strip.background = element_blank()
    )

ggsave(paste0(outdir,"barplotDOWN_GO.png"),
       plot = g.down, dpi = 300, width = 20, height = 10)
dev.off()
```

# Heatmap

```{r heatmap}
library(DESeq2)
library(tidyverse)
library(ComplexHeatmap)
library(RColorBrewer)
library(circlize)
load("/mnt/Citosina/amedina/ssalazar/meta/out/LRT-dds.RData")
load("/mnt/Citosina/amedina/ssalazar/meta/combined/namedDGElist.RData")
vsd2 <- vst(dds2, blind=FALSE)
mat <- assay(vsd2)
mm <- model.matrix(~DISEASE, colData(vsd2))
mat <- limma::removeBatchEffect(mat, batch=batch, design=mm)
assay(vsd2) <- mat

save(vsd2, file=paste0(outdir, "vsd2.RData"))

DGE <- as.data.frame(results(dds2))
dim(DGE)

DGE_names <- merge(df_names, DGE, by = c('log2FoldChange', 'pvalue', 'padj')) # getting gene names
dim(DGE_names)
DGE_names<-DGE_names[,-c(10,11,12)]


norm_counts <- as.data.frame(assay(vsd2))
dim(norm_counts)

# order dataframes

DGE_names <- DGE_names[order(DGE_names$log2FoldChange, decreasing = TRUE),]
ordered_norm <- norm_counts[ order(match(rownames(norm_counts), rownames(DGE_names))), ]

# get top genes rows
DGE.top <- DGE_names[ (DGE_names$baseMean.x > 50) & (DGE_names$padj < 0.05) & (abs(DGE_names$log2FoldChange) > 0.5), ] # 721

num_keep <- 20 # keep top n genes
rows_keep <- c(seq(1:num_keep), seq(((nrow(DGE.top)+1)-(num_keep)), nrow(DGE.top)))

rownames(DGE.top) <- DGE.top$ID
rownames(ordered_norm) <- gsub("\\..*","", rownames(ordered_norm))
df.list <- list(DGE.top, ordered_norm)
common_names = Reduce(intersect, lapply(df.list, row.names))
df.list = lapply(df.list, function(x) { x[row.names(x) %in% common_names,] })

DGE.top <- df.list[[1]]
ordered_norm <- df.list[[2]]

ordered_norm <- ordered_norm[ order(match(rownames(ordered_norm), rownames(DGE.top))), ]

# getting log2 value for each gene we are keeping
l2_val <- as.matrix(DGE.top[rows_keep,]$log2FoldChange)
colnames(l2_val)<- "logFC"

# color map for expression

col_logFC <- colorRamp2(c(min(l2_val),0, max(l2_val)), c('#34a624','white','#a709eb'))


colnames(ordered_norm) <- NULL
mat <- as.matrix(ordered_norm)

ha <- HeatmapAnnotation(Samples = all_data$DISEASE,
                        col = list(Samples = c('CONTROL' = '#a9e536', 'SLE' = '#f5704b')))

row_ha <- rowAnnotation(logFC = l2_val, col = list(logFC =col_logFC))


h1 <-Heatmap(mat[rows_keep,], cluster_rows = F, row_labels = DGE.top[rows_keep,]$gene_name, name = 'Norm counts', right_annotation = row_ha, top_annotation = ha, column_km = 2, border = T)
outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/"

# with 8 genes
png(paste0(outdir,'heatmap.png'), width = 2000, height  = 1000, res = 300)
  h1
dev.off()

# with 20  genes

png(paste0(outdir,'heatmap20.png'), width = 2000, height  = 2000, res = 300)
  h1
dev.off()

# with 40 genes

png(paste0(outdir,'heatmap40.png'), width = 2000, height  = 2000, res = 300)
  h1
dev.off()


# with study annotation

study_ha <-HeatmapAnnotation(Study = all_data$study,
                        col = list(Study = c('SRP062966' = '#f5a142', 'SRP073191' = '#f5ef42', 'SRP111941' = '#2ef0e9', 'SRP136102' = '#f02eb3', 'SRP168421' = '#a1645c', 'SRP296987'='#599163', 'SRP311059'='#755c91','SRP322015'='#e68a8a')))

h1 <-Heatmap(mat[rows_keep,], cluster_rows = F, row_labels = DGE.top[rows_keep,]$gene_name, name = 'Norm counts', right_annotation = row_ha, bottom_annotation = study_ha, top_annotation = ha, column_km = 2, border = T)

png(paste0(outdir,'heatmap40_study.png'), width = 2000, height  = 2000, res = 300)
  h1
dev.off()

# all genes
  
rownames(mat) <- NULL
l2_val <- as.matrix(DGE.top$log2FoldChange)
row_ha <- rowAnnotation(logFC = l2_val, col = list(logFC =col_logFC))
h2 <-Heatmap(mat, cluster_rows = F, name = 'Norm counts', bottom_annotation=study_ha, right_annotation = row_ha, top_annotation = ha, column_km = 2, border = T)
outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/"

png(paste0(outdir,'heatmapAll_studies.png'), width = 5000, height  = 10000, res = 300)
  h2
dev.off()

#####
# heatmap with top samples ordered

ordered_samples <- all_data[order(all_data$DISEASE),] # reorder all_data
ordered_samples$number <- rownames(ordered_samples)

# order count matrix
colnames(mat) <- seq(1:318)
ordered_norm <- mat[,order(match(colnames(mat), ordered_samples$number)) ]
colnames(ordered_norm) <- NULL

ha <- HeatmapAnnotation(Samples = ordered_samples$DISEASE,
                        col = list(Samples = c('CONTROL' = '#a9e536', 'SLE' = '#f5704b')))
h1 <-Heatmap(mat[rows_keep,], cluster_rows = F, cluster_columns = F, row_labels = DGE.top[rows_keep,]$gene_name, name = 'Norm counts', right_annotation = row_ha, bottom_annotation = study_ha, top_annotation = ha)

png(paste0(outdir,'heatmap_ordered40.png'), width = 2000, height  = 2000, res = 300)
  h1
dev.off()

```


# heatmap row (gene) clustering

```{r}
ha <- HeatmapAnnotation(Samples = all_data$DISEASE,
                        col = list(Samples = c('CONTROL' = '#a9e536', 'SLE' = '#f5704b')))
rownames(mat) <- NULL
colnames(mat) <- NULL

col_fun = colorRamp2(c(-2, 0, 2), c("blue", "white", "red"))
h3 <-Heatmap(mat, name = 'Norm counts', top_annotation = ha, column_km = 2, border = T,
             col = col_fun)

outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/"

png(paste0(outdir,'heatmapAll_Rows.png'), width = 5000, height  = 10000, res = 300)
  h3
dev.off()

h3 <-Heatmap(mat[rows_keep,], name = 'Norm counts', top_annotation = ha, column_km = 2, border = T)
png(paste0(outdir,'heatmap_Rows.png'), width = 5000, height  = 10000, res = 300)
  h3
dev.off()
```

# heatmap of GO results

```{r heatmap GO terms}
library(enrichplot)
library(DOSE)
library(clusterProfiler)
library(ggplot2)
library(tidyverse)
library(org.Hs.eg.db)

load("/mnt/Citosina/amedina/ssalazar/meta/combined/namedDGElist.RData")
load("/mnt/Citosina/amedina/ssalazar/meta/out/LRT-dds.RData")

data <- df_names %>% 
  mutate(Expression = case_when(log2FoldChange >= 1 & padj < 0.05 ~ "Up-regulated",
                                log2FoldChange <= -1 & padj < 0.05 ~ "Down-regulated",
                                TRUE ~ "Unchanged"))


keytypes(org.Hs.eg.db)
original_gene_list = data$log2FoldChange
names(original_gene_list) <- data$ID
ids <- bitr(names(original_gene_list), fromType = 'ENSEMBL', toType = 'ENTREZID', OrgDb = 'org.Hs.eg.db')



#dedup_ids = ids[!duplicated(ids[c("ENSEMBL")]),]
#data <- data[!duplicated(data$ID),]
#data2 = data[data$ID %in% dedup_ids$ENSEMBL,]
#data2$Y = dedup_ids$ENTREZID
#names(kegg_gene_list) <- data2$Y
#kegg_gene_list<-na.omit(kegg_gene_list)
#kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

# Enrichment analysis


#gseK <- gseKEGG(geneList = kegg_gene_list,
                #nPerm = 10000,
               # organism = "hsa",
                #nPerm = 10000,
                #minGSSize = 2,
                #maxGSSize = 500,
                #pvalueCutoff = 0.05,
                #pAdjustMethod = "fdr",
                #keyType = 'kegg')
#save(gseK, file = paste0(outdir, 'gseKEGG.RData'))

gseK2 <- gseKEGG(geneList = kegg_gene_list,
                #nPerm = 10000,
                organism = "hsa",
                nPerm = 10000,
                minGSSize = 10,
                maxGSSize = 500,
                pvalueCutoff = 0.05,
                pAdjustMethod = "fdr",
                keyType = 'kegg', 
                by = 'DOSE')
#save(gseK2, file = paste0(outdir, 'gseKEGG2.RData'))

#gseK3 <- gseKEGG(geneList = kegg_gene_list,
                #nPerm = 10000,
                #organism = "hsa",
                #nPerm = 10000,
                #minGSSize = 3,
                #maxGSSize = 500,
                #pvalueCutoff = 0.05,
                #pAdjustMethod = "fdr",
                #keyType = 'ncbi-geneid')

#save(gseK3, file = '/mnt/Citosina/amedina/ssalazar/meta/out/combined/gseKEGG3.RData')
#load('/mnt/Citosina/amedina/ssalazar/meta/combined/gseKEGG3.RData')


#symbolKEGG_results <- setReadable(gseK3, OrgDb = org.Hs.eg.db, keyType="ENTREZID")



#######

# GET TOP GENES

top <- 70
top_genes <- bind_rows(data %>% 
    filter(Expression == 'Up-regulated') %>% 
    arrange(padj, desc(abs(log2FoldChange))) %>% 
    head(top),
  data %>% 
    filter(Expression == 'Down-regulated') %>% 
    arrange(padj, desc(abs(log2FoldChange))) %>% 
    head(top)
)

DGE_genes <- data[data$Expression != 'Unchanged',]


list_lab <- DGE_genes[,c(8,10,3)]
write.csv(list_lab, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/topGenes_list.csv')

list_lab_up <- list_lab[list_lab$Expression == 'Up-regulated',]
list_lab_up <- list_lab_up[order(-list_lab_up$log2FoldChange), ]
rownames(list_lab_up) <- seq(1:nrow(list_lab_up))

list_lab_down <- list_lab[list_lab$Expression == 'Down-regulated',]
list_lab_down <- list_lab_down[order(list_lab_down$log2FoldChange), ]
rownames(list_lab_down) <- seq(1:nrow(list_lab_down))

write.csv(list_lab_up, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/topGenesUp_list.csv')
write.csv(list_lab_down, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/topGenesDown_list.csv')

######

sigGenes <- top_genes$gene_name
original_gene_list <- top_genes$log2FoldChange
names(original_gene_list) <- top_genes$ID
# names(original_gene_list) <- top_genes$gene_name
ids <- bitr(names(original_gene_list), fromType = 'ENSEMBL', toType = 'ENTREZID', OrgDb = 'org.Hs.eg.db')
dedup_ids = ids[!duplicated(ids[c("ENSEMBL")]),]
top_genes <- top_genes[!duplicated(top_genes$ID),]
data2 = top_genes[top_genes$ID %in% dedup_ids$ENSEMBL,]
data2$Y = dedup_ids$ENTREZID
names(original_gene_list) <- data2$Y

#### 
# GO
go_gene_list<-na.omit(original_gene_list)
go_gene_list = sort(go_gene_list, decreasing = TRUE)
save(go_gene_list, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/GO_gene_list.RData')

gseGO_res <- gseGO(geneList = go_gene_list,
                ont = 'ALL',
                OrgDb = org.Hs.eg.db,
                minGSSize = 3,
                maxGSSize = 500,
                pvalueCutoff = 0.05,
                pAdjustMethod = "fdr",
                keyType = 'ENTREZID')
save(gseGO_res, file = "/mnt/Citosina/amedina/ssalazar/meta/combined/GO_results.RData")

########
########

# GO with all DE genes

sigGenes <- DGE_genes$gene_name
original_gene_list <- DGE_genes$log2FoldChange
names(original_gene_list) <- DGE_genes$ID

# names(original_gene_list) <- top_genes$gene_name
ids <- bitr(names(original_gene_list), fromType = 'ENSEMBL', toType = 'ENTREZID', OrgDb = 'org.Hs.eg.db')
dedup_ids = ids[!duplicated(ids[c("ENSEMBL")]),]
DGE_genes <- DGE_genes[!duplicated(DGE_genes$ID),]
data2 = DGE_genes[DGE_genes$ID %in% dedup_ids$ENSEMBL,]
data2$Y = dedup_ids$ENTREZID
names(original_gene_list) <- data2$Y

go_gene_list<-na.omit(original_gene_list)
go_gene_list = sort(go_gene_list, decreasing = TRUE)
save(go_gene_list, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/GO_allDEG_list.RData')

gseGO_res <- gseGO(geneList = go_gene_list,
                ont = 'ALL',
                OrgDb = org.Hs.eg.db,
                minGSSize = 3,
                maxGSSize = 500,
                pvalueCutoff = 0.05,
                pAdjustMethod = "fdr",
                keyType = 'ENTREZID')
save(gseGO_res, file = "/mnt/Citosina/amedina/ssalazar/meta/combined/GO_allDEG_results.RData")

########
########

symbolGO_results <- setReadable(gseGO_res, OrgDb = org.Hs.eg.db, keyType="ENTREZID")
symbolGO_results <- symbolGO_results@result

gseSubset <- subset(symbolGO_results, p.adjust <= 0.05 )

annGSEA <- data.frame(row.names = sigGenes)
for (j in 1:length(sigGenes)) {
  gene <- sigGenes[j]
  pattern <- gene
  for (k in 1:nrow(gseSubset)){ # parse through GO terms 
    if (any(grepl(pattern, gseSubset$core_enrichment[k]))) {
      annGSEA[j,k] <- 1
    } else {
      annGSEA[j,k] <- 0
    }
  }
}
colnames(annGSEA) <- gseSubset[,3]
# remove terms with no overlapping genes
annGSEA <- annGSEA[,apply(annGSEA, 2, mean)!=0]

# remove genes with no overlapping terms
annGSEA <- annGSEA[apply(annGSEA, 1, mean)!=0,]

annGSEA[1:5,1:5]

save(annGSEA, file = '/mnt/Citosina/amedina/ssalazar/meta/combined/annGSEA_allDEG_GO.RData')
```

```{r annGSEA}
# match the order of rownames in top_genes with annGSEA
rownames(top_genes) <- top_genes$gene_name
topTableAligned <- top_genes[which(rownames(top_genes) %in% rownames(annGSEA)),]
topTableAligned <- topTableAligned[match(rownames(annGSEA), rownames(topTableAligned)),]
all(rownames(topTableAligned) == rownames(annGSEA)) # TRUE

### all DEG

rownames(DGE_genes) <- DGE_genes$gene_name
topTableAligned <- DGE_genes[which(rownames(DGE_genes) %in% rownames(annGSEA)),]
topTableAligned <- topTableAligned[match(rownames(annGSEA), rownames(topTableAligned)),]
all(rownames(topTableAligned) == rownames(annGSEA)) # TRUE

```

# Heatmap

```{r heatmap expression}
require(ComplexHeatmap)
require(circlize)

# colour bar for -log10(adjusted p-value) for sigGenes
#dfMinusLog10FDRGenes <- data.frame(-log10(
 # topTableAligned[which(rownames(topTableAligned) %in% rownames(annGSEA)), 'padj']))
#dfMinusLog10FDRGenes[dfMinusLog10FDRGenes == 'Inf'] <- 0

# colour bar for fold changes for sigGenes
dfFoldChangeGenes <- data.frame(
  topTableAligned[which(rownames(topTableAligned) %in% rownames(annGSEA)), 'log2FoldChange'])

# merge both
dfGeneAnno <- data.frame(dfFoldChangeGenes)
colnames(dfGeneAnno) <- c('Log2FC')

colours <- colorRamp2(c(min(dfGeneAnno$Log2FC),0, max(dfGeneAnno$Log2FC)), c('royalblue','white','#b50f04'))

haGenes <- rowAnnotation(
  df = dfGeneAnno,
  col = list(Log2FC =colours),
  width = unit(1,'cm'),
  annotation_name_side = 'top')

# bottom annotation with enriched terms

haTerms <- HeatmapAnnotation(
  text = anno_text(
    colnames(annGSEA),
    rot = 45,
    just = 'right',
    gp = gpar(fontsize = 12)),
  annotation_height = unit(8, 'cm'),
  annotation_name_side = 'left')


# HEATMAP

annGSEA <- as.matrix(annGSEA)
hmapGSEA <- Heatmap(annGSEA,
  name = 'GO enrichment',
  # split = dfGeneAnno[,2],

  col = c('0' = 'white', '1' = 'forestgreen'),

  rect_gp = gpar(col = 'grey85'),

  cluster_rows = TRUE,
  show_row_dend = TRUE,
  row_title = 'Top Genes',
  row_title_side = 'left',
  row_title_gp = gpar(fontsize = 11, fontface = 'bold'),
  row_title_rot = 90,
  show_row_names = TRUE,
  row_names_gp = gpar(fontsize = 11, fontface = 'bold'),
  row_names_side = 'left',
  row_dend_width = unit(35, 'mm'),

  cluster_columns = TRUE,
  show_column_dend = TRUE,
  column_title = 'Enriched terms',
  column_title_side = 'top',
  column_title_gp = gpar(fontsize = 12, fontface = 'bold'),
  column_title_rot = 0,
  show_column_names = FALSE,

  show_heatmap_legend = FALSE,

  clustering_distance_columns = 'euclidean',
  clustering_method_columns = 'ward.D2',
  clustering_distance_rows = 'euclidean',
  clustering_method_rows = 'ward.D2',

  bottom_annotation = haTerms
  )

png(filename = "/mnt/Citosina/amedina/ssalazar/meta/combined/GOenriched_allDEG_HMap.png", width = 5000, height = 5000, res = 300)
  draw(hmapGSEA + haGenes,
    heatmap_legend_side = 'right',
    annotation_legend_side = 'right')
dev.off()
```

# directed acyclic graph

```{r GO terms graph}
library('DOSE')
library('DESeq2')
library('enrichplot')
library('ggnewscale')
load("/Users/sofiasalazar/clusterliigh/meta/combined/namedDGElist.RData")
load("/Users/sofiasalazar/clusterliigh/meta/combined/GO_gene_list.RData")


symbolGO_results <- setReadable(gseGO_res, OrgDb = org.Hs.eg.db, keyType="ENTREZID")

cnt_enrichment <- cnetplot(symbolGO_results, showCategory = 5, categorySize="geneNum", foldChange = go_gene_list, colorEdge = TRUE)

outdir = "/Users/sofiasalazar/Desktop/LAB/meta-analysis-SLE/combined/figures/"

ggsave(paste0(outdir,"cnt_enrichmentUP.png"), width = 3000, height = 5000, units = 'px', dpi = 300, bg = "white", plot = cnt_enrichment)
dev.off()

p3 <- cnetplot(symbolGO_results, foldChange=go_gene_list, circular = TRUE, colorEdge = TRUE) 
ggsave(paste0(outdir,"cnt_circle_enrichmentUP.png"), width = 3000, height = 5000, units = 'px', dpi = 300, bg = "white", plot = p3)
dev.off()
```

# PCA

```{r PCA with ellipse}
library(DESeq2)
library(ggplot2)
load('/mnt/Citosina/amedina/ssalazar/meta/out/LRT-dds.RData')
load("/mnt/Citosina/amedina/ssalazar/meta/combined/vsd2.RData")
mat <- as.matrix(assay(vsd2))
pc <- prcomp(t(mat))
dtp <- data.frame('DISEASE' = all_data$DISEASE, pc$x[,1:2])

pcaData <- plotPCA(vsd2, 'DISEASE', returnData = TRUE)

pcaData <- tibble::rownames_to_column(pcaData, "study")

percentVar <- round(100 * attr(pcaData, "percentVar"))
pca_plot <- ggplot(pcaData, aes(PC1, PC2, color=group, group = group)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  stat_ellipse()

png(file = '/mnt/Citosina/amedina/ssalazar/meta/combined/PCA-ellipse.png')
  pca_plot
dev.off()
```

# Violin plot of norm counts

```{r violin plot}
library(ggplot2)
library(DESeq2)
library(tidyverse)
library(perm)
load('/mnt/Citosina/amedina/ssalazar/meta/out/LRT-dds.RData')
load("/mnt/Citosina/amedina/ssalazar/meta/combined/vsd2.RData")
load("/mnt/Citosina/amedina/ssalazar/meta/combined/namedDGElist.RData")

head(df_names)

# name norm matrix with gene name
norm_counts <- as.data.frame(assay(vsd2))
norm_counts <- tibble::rownames_to_column(norm_counts, "ID")
name_short<-function(table){
  table$ID <- gsub("\\..*","", table$ID)
  return(table)
}

norm_counts_id <- name_short(norm_counts)

norm_counts_name <- inner_join(norm_counts_id, df_names, by = 'ID')

norm_counts_name<- norm_counts_name[,-c(1,320:327)]
rownames(norm_counts_name) <- df_names$gene_name

write.csv(norm_counts_name, "/mnt/Citosina/amedina/ssalazar/meta/combined/normcounts_name.csv")

###### 

# Boxplots
norm_counts_name <- read.csv('/Users/sofiasalazar/Desktop/LAB/meta-analysis-SLE/combined/normcounts_name.csv')
all_data <-  read.csv('/Users/sofiasalazar/Desktop/LAB/meta-analysis-SLE/combined/all_data.csv')
outdir = '/Users/sofiasalazar/Desktop/LAB/meta-analysis-SLE/combined/figures/'

rownames(norm_counts_name) <- norm_counts_name$X
norm_counts_name<-norm_counts_name[,-c(1)]

list.genes <- c("IFI27","BANK1","BLK","C1QA","C1QB","C1QC","C2","FCGR2A","FCGR3A","IRF5","ITGAM","LYN","STAT4","SLC1A7","TREX1","DNASE1L3","TLR7","TLR9","IFI44L","IL12RB2",'HLA-A','HLA-B','HLA-C')

for (i in 1:length(list.genes)){
  gene <- list.genes[i]
  counts.gene <- norm_counts_name[rownames(norm_counts_name)==gene,]
  counts.gene<- as.data.frame(t(counts.gene))
  
  # test
  expression = counts.gene[,1]
  sample = all_data$DISEASE
  df.gene <- data.frame(expression, sample)
  
  control.e <- df.gene[df.gene$sample=='CONTROL',]$expression
  sle.e<- df.gene[df.gene$sample=='SLE',]$expression
  test <- permTS(control.e, sle.e)

  # wilcox.test(x = control.e, y = sle.e, alternative = "two.sided", mu = 0,
            # paired = FALSE, conf.int = 0.95)
  if(test$p.value < 0.05){
    print(gene)
    # plot
    
    p <- ggplot(df.gene, aes(x=sample, y=expression, fill=sample)) + 
    geom_violin(trim=FALSE) +
    labs(title=gene,x = NULL, y="Normalized counts") +
    ylim(0,18)
    
    p1 <- p + geom_boxplot(width=0.05, color = 'black', fill='gray') +
   # geom_jitter(shape=16, position=position_jitter(0.2)) +
    scale_fill_manual(values=c("#e65a5a", "#4d80c4")) +
    stat_summary(fun.y=mean, geom = 'point', shape = 23, size = 2) +
    theme_classic()
    
    p2 <- p1 + theme(legend.position="none") +
    annotate("text",
           x = 1:length(table(df.gene$sample)),
           y = 17,
           label = paste0('n = ', table(df.gene$sample)),
           col = "black",
           vjust = - 1)

  p3 <- p2 + annotate("text",
           x = 1,
           y = 15,
           label = paste0('Perm test, p = ', signif(test$p.value, digits = 4)),
           col = "black",
           vjust = - 1)

  ggsave(paste0("/Users/sofiasalazar/Desktop/LAB/meta-analysis-SLE/combined/figures/violinplot",gene,"-ptest.png"), dpi = 300, plot = p3)  

  }
}

```

# barplots for number of DE all genes with lnc

```{r}
library(tidyverse)
library(ggplot2)
outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/"
DGE.list <- read.csv("/mnt/Citosina/amedina/ssalazar/meta/combined/DGElist_withNames_noncoding.csv")
DGE.list <- DGE.list[,-1]

diffexpressed1 <- subset(DGE.list, padj < 0.05 & (log2FoldChange > 1 | log2FoldChange < -1 ))
diffexpressed2 <- subset(DGE.list, padj < 0.05 & (log2FoldChange > 2 | log2FoldChange < -2 ))

levels(as.factor(diffexpressed1$transcript_biotype))
count.types1 <- as.data.frame(table(diffexpressed1$transcript_biotype))
keep1 <- c("lncRNA","miRNA","protein_coding","protein_coding_CDS_not_defined","snoRNA","snRNA")
df1.small <-count.types1[count.types1$Var1 %in% keep1,]

levels(as.factor(diffexpressed2$transcript_biotype))
count.types2 <- as.data.frame(table(diffexpressed2$transcript_biotype))
keep2 <- c("lncRNA","protein_coding","protein_coding_CDS_not_defined")
df2.small <-count.types2[count.types2$Var1 %in% keep2,]


## barplots

p <- ggplot(data = df1.small, aes(x = Var1, y = Freq)) + 
  geom_bar(stat = 'identity', fill = '#5d996c') + 
  geom_text(aes(label = Freq, vjust = -0.3, size = 3.5)) +
  coord_flip() +
  labs(title="Log2FoldChange < or > 1",x = NULL, y = "Frequency") +
  theme_classic() +
  theme(legend.position="none")

outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/figures/"
ggsave(paste0(outdir, "biotypes_barplot.png"), plot = p, dpi = 300)

p2 <- ggplot(data = df2.small, aes(x = Var1, y = Freq)) + 
  geom_bar(stat = 'identity', fill = '#a1506c') + 
  geom_text(aes(label = Freq, vjust = -0.3, size = 3.5)) +
  coord_flip() +
  labs(title="Log2FoldChange < or > 2",x = NULL, y = "Frequency") +
  theme_classic() +
  theme(legend.position="none")

ggsave(paste0(outdir, "biotypes_barplot_2.png"), plot = p2, dpi = 300)
```

# GWAS catalog genes

```{r GWAS catalog curation}
library(tidyverse)
# mixed populations
GWAS.catalog.df <- read.csv("/Users/sofiasalazar/Desktop/LAB/GWASCathalogSLE-Mixed\ populations.csv")
rep.gene <- GWAS.Xcatalog.df$MAPPED_GENE
gwas.genes <- list()
for (i in 1:length(rep.gene)){
  entry <- rep.gene[i]
  gwas.genes[i] <- str_split(entry, " - ")
}
mixed.genes <- unlist(gwas.genes)
mixed.genes.df <- as.data.frame(table(mixed.genes))
top.mixed <- subset(mixed.genes.df, Freq >= 4)
top.mixed

a <- unique(GWAS.catalog.df[str_detect(GWAS.catalog.df$MAPPED_GENE, 'ATG5'),]$PUBMEDID)


## european

GWAS.catalog.df <- read.csv("/Users/sofiasalazar/Desktop/LAB/GWASCathalogSLE-European.csv")
rep.gene <- GWAS.catalog.df$MAPPED_GENE
gwas.genes <- list()
for (i in 1:length(rep.gene)){
  entry <- rep.gene[i]
  gwas.genes[i] <- str_split(entry, " - ")
}
eu.genes <- unlist(gwas.genes)
eu.genes.df <- as.data.frame(table(eu.genes))
top.eu <- subset(eu.genes.df, Freq >= 4)
(top.eu)

b <- unique(GWAS.catalog.df[str_detect(GWAS.catalog.df$MAPPED_GENE, 'ATG5'),]$PUBMEDID)

## asian

GWAS.catalog.df <- read.csv("/Users/sofiasalazar/Desktop/LAB/GWASCathalogSLE-Asians.csv")
rep.gene <- GWAS.catalog.df$MAPPED_GENE
gwas.genes <- list()
for (i in 1:length(rep.gene)){
  entry <- rep.gene[i]
  gwas.genes[i] <- str_split(entry, " - ")
}
a.genes <- unlist(gwas.genes)
a.genes.df <- as.data.frame(table(a.genes))
top.a <- subset(a.genes.df, Freq >= 4)
top.a
c <- unique(GWAS.catalog.df[str_detect(GWAS.catalog.df$MAPPED_GENE, 'ATG5'),]$PUBMEDID)

unique(c(a,b,c))

## nat american
#GWAS.catalog.df <- read.csv("/Users/sofiasalazar/Desktop/LAB/GWASCathalogSLE-NatAm.csv")
  #rep.gene <- GWAS.catalog.df$MAPPED_GENE
#gwas.genes <- list()
#for (i in 1:length(rep.gene)){
  #entry <- rep.gene[i]
  #gwas.genes[i] <- str_split(entry, " - ")
#}
#natam.genes <- unlist(gwas.genes)
#natam.genes.df <- as.data.frame(table(natam.genes))
#top.natam <- subset(natam.genes.df, Freq > 1)
#top.natam
```

# Gene functional categories

```{r}
load('/mnt/Citosina/amedina/ssalazar/meta/combined/GO_allDEG_results.RData')
load('/mnt/Citosina/amedina/ssalazar/meta/combined/annGSEA_allDEG_GO.RData')
head(annGSEA)
head(gseGO_res)

symbolGO_results <- setReadable(gseGO_res, OrgDb = org.Hs.eg.db, keyType="ENTREZID")
symbolGO_results <- symbolGO_results@result
gseSubset <- subset(symbolGO_results, p.adjust <= 0.05 )
write.csv(as.data.frame(gseSubset), '/mnt/Citosina/amedina/ssalazar/meta/combined/gseDF_all_DEG.csv')

```

