---
title: "Differential Expression"
author: "Sofia Salazar"
date: "2023-02-06"
output: html_document
---

# Intro

In this script, we:

1. get the curated RSE object for each experiment, get the counts and combine them into a single data frame.

2. Visualize raw counts with a PCA.

3. Perform differential expression analysis with DESeq2 + limma::removeBatchEffect

# Libraries

```{r}
library(tidyverse)
library(SummarizedExperiment)
library(ggplot2)
```


```{r}
# load counts

counts_file <- readRDS("/mnt/Citosina/amedina/ssalazar/meta/out/curated_rse.xz")
all_counts <- list()
for (i in 1:length(counts_file)){
  counts<-as.matrix(assays(counts_file[[i]])$counts) # with transformed counts
  # filtering low counts
  # keep<-rowSums(counts)>10
  # counts <- counts[keep,]
  # keep <- rowSums(counts >= 10) >= 3
  # counts <- counts[keep,]
  all_counts[[i]]<-as.data.frame(counts)
  all_counts[[i]] <- tibble::rownames_to_column(all_counts[[i]], 'ID')
}
```


```{r}
# Combining counts in one data frame
full_counts <- all_counts %>% 
  purrr::reduce(full_join, by = 'ID')
```


```{r}
# batch - sample relation dataframe
studies <- names(counts_file)
data <- list()
for (i in 1:length(studies)){
  samples <- colnames(counts_file[[i]])
  DISEASE <- counts_file[[i]]$DISEASE
  study <- rep(studies[i], length(samples))
  data[[i]] <- data.frame(samples, DISEASE, study)
}

all_data <- do.call("rbind", data)
write.csv(all_data, file = "/mnt/Citosina/amedina/ssalazar/meta/combined/all_data.csv")
```

# PCA for raw counts

```{r}
outdir = "/mnt/Citosina/amedina/ssalazar/meta/combined/figures/"
pca_matrix <- t(dge$counts) # rows = samples, columns = genes
pc <- prcomp(pca_matrix)
dtp <- data.frame('study' = all_data$study, 'DISEASE' = all_data$DISEASE, pc$x[,1:2]) # the first two componets are selected
pov <- pc$sdev^2 / sum(pc$sdev^2)
p <- ggplot(data = dtp, group = DISEASE) + 
    geom_point(aes(x = PC1, y = PC2, col = study, shape = DISEASE, size = 3)) +
    theme_gray()
png(file = paste0(outdir, "allStudiesNormalized-pca.png"), width = 800, height = 800)
  p + ggtitle("PCA for normalized counts") +
    xlab(paste0("PC1 (", round(pov[1]*100,2), "%)")) + ylab(paste0("PC2 (", round(pov[2]*100,2),"%)"))
  dev.off()
```


## DESEQ with batch as covariate + limma::removeBatchEffect

```{r}
library(DESeq2)
all_data$batch <- as.factor(as.numeric(as.factor(all_data$study)))
count_matrix <- as.matrix(full_counts[,-1])
rownames(count_matrix)<-full_counts$ID

dds2 <- DESeqDataSetFromMatrix(countData = count_matrix, colData=all_data, design= ~batch+DISEASE)
dds2 <- DESeq(dds2, test="LRT", reduced=~batch)
keep <- rowSums(counts(dds2)) >= 10
dds2 <- dds2[keep,]
res2 <- results(dds2) # DGE accounting for batch


vsd2 <- vst(dds2, blind=FALSE)

mat <- assay(vsd2)
mm <- model.matrix(~DISEASE, colData(vsd2))
mat <- limma::removeBatchEffect(mat, batch=batch, design=mm)
assay(vsd2) <- mat

save(vsd2, file="/mnt/Citosina/amedina/ssalazar/meta/combined/vsd2.RData")
```


```{r}
save.image(file = "/mnt/Citosina/amedina/ssalazar/meta/combined/LRT-dds.RData")
```

